#! /bin/sh

#     __                                          
#    / /_  _________ _      ______ ___  __________
#   / __ \/ ___/ __ \ | /| / / __ `__ \/ ___/ ___/
#  / /_/ (__  ) /_/ / |/ |/ / / / / / / /  / /__  
# /_.___/____/ .___/|__/|__/_/ /_/ /_/_/   \___/
#
# Influence from: https://github.com/Barbarossa93/Forester/blob/main/.config/bspwm/bspwmrc
# My dofiles: My dotfiles: https://github.com/cullyn-inverba/dotfiles

pgrep -x sxhkd > /dev/null || sxhkd & ~/.config/bspwm/borders

bspc monitor -d 1 2 3 4

bspc config border_width        12
bspc config top_padding         36
bspc config right_padding       -4
bspc config left_padding        -4
bspc config bottom_padding      -4
bspc config window_gap          16
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a youtube-music-desktop-app desktop='^2'state=floating 
bspc rule -a Chromium desktop='^1'
