#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

# .--.      .-'.      .--.      .--.      .--.      .--.      .`-.
#|:::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::::.\
#|::::.\:: https://github.com/cullyn-inverba/dotfiles ::.\::::::::.\
#|:::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::::.\::::::::.\
#        `--'      `.-'      `--'      `--'      `--'      `-.'      `

# ╔═╗┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ╠═╣│ │ │ │ │└─┐ │ ├─┤├┬┘ │ 
# ╩ ╩└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴ 
bspc rule -r '*'
killall "dunst"
dunst &
killall "sxhkd"
sxhkd &
~/.config/polybar/launch.sh &
killall "borders"
~/.config/bspwm/borders &
feh --bg-scale ~/resources/wallpapers/'arrival-3840x2160.jpg' &
ytmdesktop &
#notify-send -u low bspwm restarted &

# ╔╦╗┌─┐┌─┐┬┌─┌┬┐┌─┐┌─┐┌─┐
#  ║║├┤ └─┐├┴┐ │ │ │├─┘└─┐
# ═╩╝└─┘└─┘┴ ┴ ┴ └─┘┴  └─┘
bspc monitor -d 1 2 3 4
bspc rule -a youtube-music-desktop-app desktop='^4' state=floating

bspc rule -a Zathura state=tiled 
bspc rule -a vlc state=floating

# ╔╗ ┌─┐┬ ┬┌─┐┬  ┬┬┌─┐┬─┐
# ╠╩╗├┤ ├─┤├─┤└┐┌┘││ │├┬┘
# ╚═╝└─┘┴ ┴┴ ┴ └┘ ┴└─┘┴└─
bspc config focus_follows_pointer   true 
bspc config split_ratio             0.52

# ╔╗ ┌─┐┬─┐┌┬┐┌─┐┬─┐┌─┐
# ╠╩╗│ │├┬┘ ││├┤ ├┬┘└─┐
# ╚═╝└─┘┴└──┴┘└─┘┴└─└─┘
bspc config focused_border_color    "#1f1f1f" 
bspc config normal_border_color     "#1f1f1f" 
bspc config active_border_color     "#1f1f1f" 
bspc config border_width            10

# ╔═╗┌─┐┌┬┐┌┬┐┬┌┐┌┌─┐
# ╠═╝├─┤ ││ │││││││ ┬
# ╩  ┴ ┴─┴┘─┴┘┴┘└┘└─┘
bspc config window_gap          16
bspc config top_padding         48
bspc config right_padding       4
bspc config left_padding        4
bspc config bottom_padding      4

# ╔╦╗┌─┐┌┐┌┌─┐┌─┐┬  ┌─┐
# ║║║│ │││││ ││  │  ├┤ 
# ╩ ╩└─┘┘└┘└─┘└─┘┴─┘└─┘
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config paddingless_monocle     false
bspc config top_monocle_padding     169
bspc config right_monocle_padding   420
bspc config left_monocle_padding    420
bspc config bottom_monocle_padding  169